FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV HF_HOME=/app/.cache/huggingface
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
